### ISSUE TITLE
My door sensors, motion sensors and environmental sensors are not working

### ISSUE THREAD

**Issue by huynguyendt1** [MapleEve/lifesmart-HACS-for-hass#1]
![image](https://github.com/MapleEve/lifesmart-HACS-for-hass/assets/61014554/2ead8484-000f-42e7-98d7-0d50351d2817)

**Comment by MapleEve** [comment]
Please start a debug log for your component and post the log here, you can erase sensitive info in it.

**Comment by MapleEve** [comment]
> ![image](https://private-user-images.githubusercontent.com/61014554/324407900-2ead8484-000f-42e7-98d7-0d50351d2817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjgyNzMsIm5iZiI6MTcxMzk2Nzk3MywicGF0aCI6Ii82MTAxNDU1NC8zMjQ0MDc5MDAtMmVhZDg0ODQtMDAwZi00MmU3LTk4ZDctMGQ1MDM1MWQyODE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE0MTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZGFiZmI5YTc3N2IxNzQ0NzFmOGUwMGM1ZTI3YWMxMmRlOWMwODkyYjMyZTRiM2Q5MTNlZjNiOGJkZWYxM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d542nNt6dAb5iVaa-yeJlDdVg5bbCG0V_26wjX4uiYc)

besides, you can redownload the main version rather than 24.04.10 to test it it's okay now

**Comment by MapleEve** [comment]
https://github.com/MapleEve/lifesmart-HACS-for-hass/releases/tag/v24.4.25

**Comment by huynguyendt1** [comment]
Ok thanks u so much :3

Vào Th 4, 24 thg 4, 2024 lúc 23:33 Maple Gao ***@***.***> đã
viết:

**Comment by MapleEve** [comment]
Should be OK now with v25.07.19 RC
